### ISSUE TITLE
Capture template for additional roles required for patroni deployment

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#374]
**Describe the task**
In order to deploy patroni, several additional actions are required above and beyond those currently specified in the edit role.

These additional actions (see context below) need to be either added to the edit role, or at least stored in a template with appropriate instructions.

**Acceptance Criteria**
- [ ] yaml template store in project
- [ ] if deemed appropriate, add roles to edit, or document/store the rolebinding.

**Additional context**
```
rules:
  - verbs:
      - get
      - create
      - list
      - delete
      - patch
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
  - verbs:
      - get
      - create
      - list
      - delete
      - patch
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
```
